### ISSUE TITLE
⭐  Checklist for `v1.0-beta.1`

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#205]
## Pre-release Checklist from [Versioning Policy](https://tides-transit.org/main/governance/policies/change-management/#releases)

- [x] Each pre-release MUST contain one or more changes to [normative content](https://tides-transit.org/main/governance/policies/change-management/#normative-content) which have been approved through the change-making process.
- [x] Each pre-release MUST be reviewed and approved in GitHub by 1+ members of the board – or their designees – for accuracy and consistency with the changes’ intent.
- [x] Pre-releases MUST be tagged with an appropriate pre-release version number
- [x] Each pre-release MUST have documentation available.
- [x] Each pre-release MUST have an entry in CHANGELOG.md.
- [x] Each pre-release MAY be [specified as a pre-release on Github](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

## Additional items for Beta release

- [x] All (planned) normative content changes completed

**Comment by e-lo** [comment]
Closed b/c completed a year ago~
