### ISSUE TITLE
Setup auto-documentation from meta-schema --> human-readable documentation (i.e. GH action which translates schema from JSON-->Markdown)

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#22]
As a maintainer, I'd like the user-oriented documentation to automagically read the schemas and convert them to markdown documentation.

Implementation thoughts:

- [ ]  host on a github pages site
- [x]  use [`mkdocs`](https://www.mkdocs.org/)
- [x]  use [`mike`](https://github.com/jimporter/mike) to view different versions
- [x]  autogenerate the site with each push using github actions* - this will also allow us to review pull requests
- [x] ...some how git from .json to markdown for schema. 

* note that this will require us to push to `main` in order to make sure it works...
