### ISSUE TITLE
Define requirements for an initial Use Case / Feature

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#32]
_As TIDES implementer, I'd like to understand what files and fields are required in order to satisfy my particular use case._ 

## Todo

- [ ] Identify a relatively straightforward AND useful use case (@jlstpaul  - suggestions?)
- [ ] Explore options for how to define the requirements for that use case which are more strict than the spec itself (@j-meelah )
- [ ] Decide how to represent the use case requirements (PMT)
- [ ] Implement (@j-meelah )

## Background

* Most files and fields are optional in the spec, but many are required if you want to be able to **do** anything with the data
* The files/fields that are required are dependent upon use-cases

Per @jlstpaul :
> I like the idea of defining "use cases" for the spec that document the files and fields required for different processes and purposes. This would allow someone to crosswalk between a given dataset, which documents the files and field included, and a given use case, to know whether the dataset supports the use case. I think this would require not just the files and fields, but also some measure of the data quality (completeness, accuracy, precision, etc.) for the data that is present.

## Potential Options for Representing

1. Additional schema file which updates the previous one (can we make one dependent on the other and just update the required fields either within frictionless or automagically in a GH action?)
  * pro: makes it easy on implementation end; could probably automagically update the markdown documentation too
  * con: something else to maintain
2. Just write it out in markdown
  * pro: easy
  * con: can't automagically validate a dataset against a use case
