### ISSUE TITLE
Add Example Data + Scripts to convert to TIDES from a California Agency

### ISSUE THREAD

**Issue by e-lo** [TIDES-transit/TIDES#79]
*As a potential TIDES user, I'd like to see examples that are relevant to my agency*

*As Cal-ITP, I'd like to facilitate the data interoperability of our constituent agencies using the TIDES specification and learn about any hurdles to implementing it as specified*

### Implementation Steps

- [ ] Confirm interest from an agency
- [ ] Obtain sample APC, AVL or AFC data dumps from raw components
- [ ] Develop scripts/middleware to convert to TIDES format

### Candidate Agencies

Per discussion with @hunterowens :

- MST
- SBMTD

**Comment by j-meelah** [comment]
Received sample APC data from SBMTD
